github.com:
    users:
        salmansamer827-cmyk:
            oauth_token: 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
    git_protocol: https
    user: salmansamer827-cmyk
    oauth_token: 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
